### ISSUE TITLE
Triplet loss `invert_best=True` -> `False`

### ISSUE THREAD

**Issue by ashlaban** [DIVA-DIA/DeepDIVA#12]
AFAIU, triplet training uses the MAP metric which ranges from 0 (bad) to 1 (good). I.e. the best value is the one with the maximum value. Hence I suspect this line of code:

https://github.com/DIVA-DIA/DeepDIVA/blob/68061031c186eda346f125cac4779e1df61c4938/template/runner/triplet/triplet.py#L130

should read
```
invert_best=False,
```
instead of True.

**Comment by Renthal** [comment]
You are indeed correct. This is a legacy bug for when we were using another metric; if you'd make a PR I accept it
