### ISSUE TITLE
Segmentation fault running setup_environment.sh when reinstalling (ubuntu)

### ISSUE THREAD

**Issue by ajoino** [DIVA-DIA/DeepDIVA#4]
Hi.

I removed the DeepDIVA and miniconda3 folder to make a clean reinstall of DeepDiva, but everytime I run setup_environment.sh it get to line 42: `echo 'source ~/.bash_functions' >> ~/.bashrc` the terminal stops, prints 'segmentation fault' and crashes. If I then try to open a new terminal, it also crashes until I remove the `source ~/.bash_functions` from my .bashrc.

Initially, the segmentation fault showed up when I deteled everything within the `>>>> initialized by conda` block. I did this because I ran setup_environment.sh a second time (I did this really just to see what would happen). The result of running setup_enviroment.sh a second time was additional `>>>> initialized by conda` blocks in my .bashrc.

I am assuming that there is some .bash_whatever or some path variable that messes things up but I do not know where to start searching.

**Comment by vinaychandranp** [comment]
Can you attach your ~/.bashrc and ~/.bash_functions here?

**Comment by ajoino** [comment]
Of course

[bash_functions.txt](https://github.com/DIVA-DIA/DeepDIVA/files/3037938/bash_functions.txt)
[bashrc.txt](https://github.com/DIVA-DIA/DeepDIVA/files/3037939/bashrc.txt)
This is the result of running setup_environment.sh a few times and removing the final `source ~/bash_functions.sh` to make bash not crash.

**Comment by vinaychandranp** [comment]
There ought to be a .bashrc-miniconda3.bak in your home folder. Can you check if that contains any lines added by Conda? 
If it does contain lines from Conda go to steps 1. Otherwise replace .bashrc with .bashrc-miniconda3.bak and go to step 2. 

1. remove the line source ~/.bash_functions from ~/.bashrc
2. remove the ~/.bash_functions 
3. Log out of all open terminals and login again.

Hopefully this should fix the issue.

**Comment by ajoino** [comment]
Yes, my .bashrc-miniconda3.bak contained `>>>> conda init` and your solution worked, thank you!

If you don't mind, could you explain what was causing the error?

**Comment by vinaychandranp** [comment]
I think it was most likely an inconsistent state of environment variables as you guessed.
