### ISSUE TITLE
Visualizing embeddings - Format to specify output

### ISSUE THREAD

**Issue by priyamshank** [DIVA-DIA/DeepDIVA#9]
Having trouble with creating a embedding to visualize. As per the DeepDIVA tutorial I use the following command, 

**python util/visualization/embedding.py --results-file /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s/results.pkl --output-file /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s --embedding tsne --tensorboard**

whereby as per instructions I specify path to output folder. This is the error I get, 

_usage: embedding.py [-h] [--results-file RESULTS_FILE]
                    [--embedding {_load_thumbnail,_main,_make_embedding,_make_folder_if_not_exists,isomap,mds,pca,tsne}]
                    [--output OUTPUT] [--3d] [--tensorboard]
embedding.py: error: unrecognized arguments: --output-file /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s_

Since it complains of unrecognized argument I looked up the embedding.py script and saw the following lines, 

`parser.add_argument('--output',
                        type=str,
                        default='./output.png',
                        help='path to generate output image')`
 
Therefore I changed the command to, 

**python util/visualization/embedding.py --results-file /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s/results.pkl --output /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s --embedding tsne --tensorboard**

Then the following error pops up, 

_Traceback (most recent call last):
  File "util/visualization/embedding.py", line 242, in <module>
    _main(args)
  File "util/visualization/embedding.py", line 192, in _main
    _make_folder_if_not_exists(os.path.dirname(args.output_file))
AttributeError: 'Namespace' object has no attribute 'output_file'_

Also tried the following, 

**(deepdiva) ghfiy@by-df547:~/DeepDIVA$ python util/visualization/embedding.py --results-file /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s/results.pkl --output_file /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s --embedding tsne --tensorboard**

_usage: embedding.py [-h] [--results-file RESULTS_FILE]
                    [--embedding {_load_thumbnail,_main,_make_embedding,_make_folder_if_not_exists,isomap,mds,pca,tsne}]
                    [--output OUTPUT] [--3d] [--tensorboard]
embedding.py: error: unrecognized arguments: --output_file /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s_

**(deepdiva) ghfiy@by-df547:~/DeepDIVA$ python util/visualization/embedding.py --results-file /home/local/DFPOC/ghfiy/DeepDIVA/output/OSRAM3/MNIST/output_channels=10/no_cuda=True/04-06-19-10h-27m-58s/results.pkl --output-file ./output.png --embedding tsne --tensorboard**

_usage: embedding.py [-h] [--results-file RESULTS_FILE]
                    [--embedding {_load_thumbnail,_main,_make_embedding,_make_folder_if_not_exists,isomap,mds,pca,tsne}]
                    [--output OUTPUT] [--3d] [--tensorboard]
embedding.py: error: unrecognized arguments: --output-file ./output.png_

and various other permutations and combinations. What would be the right way to specify this argument?

**Comment by vinaychandranp** [comment]
Could you try re-running after making these changes?

`args.output_file` to `args.output` in lines 192 and 208 of the file. 
https://github.com/DIVA-DIA/DeepDIVA/blob/master/util/visualization/embedding.py#L192
https://github.com/DIVA-DIA/DeepDIVA/blob/master/util/visualization/embedding.py#L208

After that you can specify the path to an output file/folder using `--output /path/to/folder/output.png` or `--output /path/to/folder/`

**Comment by priyamshank** [comment]
Executes! BTW apart from the above changes I also changed `if args.output.endwith('.png')` to ` if args.output.endswith('.png')` on line 195 in the same file.  

However, with the following changes the command only works with argument --tensorboard and not without to create just a image. 

I still keep the issue open because on first glance I see that my tensorbload is all empty. Says no scalar data was found. No image was found and so on. But it could be possible it is due to some issue with my remote server. Therefore I am leaving the issue open until I am sure on this aspect.

**Comment by vinaychandranp** [comment]
Thanks! We'll make sure to change that as well. But within tensor board, it's not supposed to produce anything other than in the tab Projector. But if you don't even find anything there, you might have to start your TensorBoard in the folder one level higher.

**Comment by priyamshank** [comment]
Ok so I figured out that it is not possible to run tensorboard on my server because it is not possible to activate/enable WebGL on most remote servers. Therefore as a work aound I copied the tensor.tsv and metadata.tsv into my local machine and uploaded it on https://projector.tensorflow.org/ to view the embeddings. Looks fine for now. Thank you!
